# ADLMIDI

set(WITH_MIDI_SEQUENCER OFF CACHE STRING "" FORCE)
set(WITH_MUS_SUPPORT OFF CACHE STRING "" FORCE)
set(WITH_XMI_SUPPORT OFF CACHE STRING "" FORCE)
set(WITH_EMBEDDED_BANKS OFF CACHE STRING "" FORCE)

set(libADLMIDI_STATIC ON CACHE STRING "" FORCE)
set(libADLMIDI_SHARED OFF CACHE STRING "" FORCE)
add_subdirectory("${PROJECT_SOURCE_DIR}/thirdparty/libADLMIDI" EXCLUDE_FROM_ALL)
target_compile_definitions(ADLMIDI_static PRIVATE "ADLMIDI_EXPORT=")
target_compile_definitions(ADLMIDI_static PUBLIC "ADLMIDI_UNSTABLE_API=")

set(libOPNMIDI_STATIC ON CACHE STRING "" FORCE)
set(libOPNMIDI_SHARED OFF CACHE STRING "" FORCE)
add_subdirectory("${PROJECT_SOURCE_DIR}/thirdparty/libOPNMIDI" EXCLUDE_FROM_ALL)
target_compile_definitions(OPNMIDI_static PRIVATE "OPNMIDI_EXPORT=")
target_compile_definitions(OPNMIDI_static PUBLIC "OPNMIDI_UNSTABLE_API=")
